#!/usr/bin/env python3
"""
Rebuild ../index.html from the editable source in this folder.

Edit mockup_b_template.html (the real source), then run:

    python3 _build/build.py

It injects every {{PLACEHOLDER}} — base64 images (assets.json), the three
background wallpapers (wp_*.b64.txt), the embedded Roboto Round fallback font
(roboto_round.b64.txt), the dock icons (icons.b64.json), and the francophones icon (built from ../Icon.svg) —
and writes the self-contained ../index.html that GitHub Pages serves.

The background wallpapers themselves are generated by gen_bg.py (PIL + numpy);
you only need to re-run that if you change a background mood.
"""
import re, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def read(name):
    with open(os.path.join(HERE, name)) as f:
        return f.read()


def main():
    a = json.load(open(os.path.join(HERE, "assets.json")))
    icons = json.load(open(os.path.join(HERE, "icons.b64.json")))

    # francophones icon — built from the repo-root Icon.svg (fleur-de-lys path
    # reused inside a luminance mask over a rotated taegeuk)
    raw = open(os.path.join(ROOT, "Icon.svg")).read()
    d = re.search(r'<path id="fleur-de-lys" d="([^"]+)"', raw).group(1)
    franco = (
        f'<svg class="franco-ico" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2500 2500" '
        f'role="img" aria-label="Francophones Korea logo"><defs><path id="fdl" d="{d}"/>'
        f'<mask id="fdlmask" maskUnits="userSpaceOnUse" x="0" y="0" width="2500" height="2500" '
        f'mask-type="luminance"><rect width="2500" height="2500" fill="#fff"/>'
        f'<use href="#fdl" transform="translate(490 208) scale(2.848880597)" fill="#000"/></mask></defs>'
        f'<g mask="url(#fdlmask)"><g transform="translate(1250 1250) scale(52.0833333)">'
        f'<g transform="rotate(33.69006752598)">'
        f'<path fill="#cd2e3a" d="M12 0a18 18 0 11-36 0 24 24 0 1148 0"/>'
        f'<path fill="#0047a0" d="M0 0a12 12 0 1124 0 24 24 0 11-48 0 12 12 0 1024 0"/>'
        f'</g></g></g></svg>'
    )

    html = read("mockup_b_template.html")
    rep = {
        "{{LOGO_OLD}}": a["logo_old"], "{{LOGO_NEW}}": a["logo_new"], "{{NAVER}}": a["naver"],
        "{{CONF}}": a["CONF"], "{{LEX}}": a["LEX"], "{{LYS_CLEAN}}": a["lys_clean"],
        "{{PMA_CLEAN}}": a["pma_clean"], "{{FRANCO_ICON}}": franco, "{{APRESDOCX}}": a["apresdocx"],
        "{{WP_BLEU}}": read("wp_bleu.b64.txt").strip(),
        "{{WP_VERT}}": read("wp_vert.b64.txt").strip(),
        "{{WP_SILVER}}": read("wp_silver.b64.txt").strip(),
        "{{ROBOTO_ROUND}}": read("roboto_round.b64.txt").strip(),
    }
    for i in range(1, 11):
        rep["{{NP%d}}" % i] = a["NP%d" % i]
    # 독 아이콘 — gen_icons.py 가 레포 루트의 .icns 에서 만들어 둔 base64 PNG
    for k, v in icons.items():
        rep["{{%s}}" % k] = v

    for k, v in rep.items():
        assert k in html, "MISSING placeholder in template: " + k
        html = html.replace(k, v)

    leftover = re.findall(r"\{\{[A-Z0-9_]+\}\}", html)
    assert not leftover, "unfilled placeholders remain: " + str(leftover)

    # Wrap in a proper HTML document. The template is authored as page *content*
    # (it starts at <title>) because when it's published as a Claude Artifact the
    # host wraps it in a <head>/<body> skeleton. GitHub Pages serves index.html
    # raw, so without an explicit <meta name="viewport"> mobile browsers fall back
    # to a ~980px desktop layout and shrink it. Add the head here (and a clean
    # <title>), stripping the template's inline mockup <title>.
    body = re.sub(r"^<title>.*?</title>\s*", "", html, count=1, flags=re.DOTALL)
    doc = (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n'
        "<title>Jiwon Shin</title>\n"
        "</head>\n"
        "<body>\n"
        + body +
        "\n</body>\n</html>\n"
    )

    out = os.path.join(ROOT, "index.html")
    with open(out, "w") as f:
        f.write(doc)
    print("wrote", out, len(doc) // 1024, "KB")


if __name__ == "__main__":
    main()
